name: Release artifact for Linux

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release_artifact:
    name: Release artifact for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
          architecture: x64
      - name: "Run mvn clean javafx:jlink"
        run: "mvn clean javafx:jlink"
      - name: Create directory for packaging and copy required files to there
        run: |
          mkdir -p ./Miffie/Data/Java
          cp -r ./Data ./Miffie/
          cp -r ./target/app ./Miffie/Data/Java/
          cp -r ./target/classes ./Miffie/Data/Java/
          cp ./miffie.sh ./Miffie/
      - name: Copy laucher script to use 'javaw'
        run: cp ./appw ./Miffie/Data/Java/app/bin/appw
      - name: Create tar.gz file (miffie_${{github.ref_name}}_linux_x64.tar.gz)
        run: tar -zcf miffie_${{github.ref_name}}_linux_x64.tar.gz ./Miffie
      - name: Publish artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: miffie_${{github.ref_name}}_linux_x64.tar.gz
