name: Release artifact for macOS

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release_artifact:
    name: Release artifact for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
          architecture: x64
      - name: "Run mvn clean javafx:jlink"
        run: "mvn clean javafx:jlink"
      - name: Create directory for packaging and copy required files to there
        run: |
          rsync -a ./Data ./Miffie
          rsync -a ./target/app ./Miffie/Data/Java
          rsync -a ./target/classes ./Miffie/Data/Java
          cp ./miffie.sh ./Miffie/
      - name: Create tar.gz file (miffie_${{github.ref_name}}_macos_x64.tar.gz)
        run: tar -zcf miffie_${{github.ref_name}}_macos_x64.tar.gz ./Miffie
      - name: Publish artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: miffie_${{github.ref_name}}_macos_x64.tar.gz
