name: Release artifact for Windows

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release_artifact:
    name: Release artifact for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
          architecture: x64
      - name: "Run mvn clean javafx:jlink"
        run: "mvn clean javafx:jlink"
      - name: Create directory for packaging and copy required files to there
        shell: powershell
        run: |
          New-Item -Path . -Name .\Miffie\Data\Java -ItemType directory
          Copy-Item -Path .\Data -Destination .\Miffie\ -Recurse
          Copy-Item -Path .\target\app -Destination .\Miffie\Data\Java\ -Recurse
          Copy-Item -Path .\target\classes -Destination .\Miffie\Data\Java\ -Recurse
          Copy-Item -Path .\miffie.bat -Destination .\Miffie\
      - name: Copy laucher script to use 'javaw'
        shell: powershell
        run: Copy-Item -Path .\appw.bat -Destination .\Miffie\Data\Java\app\bin\appw.bat
      - name: Create zip file (miffie_${{steps.get_tag.outputs.tag}}_windows_x64.zip)
        shell: powershell
        run: Compress-Archive -Path .\Miffie -DestinationPath .\miffie_${{steps.get_tag.outputs.tag}}_windows_x64.zip
      - name: Publish artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: miffie_${{steps.get_tag.outputs.tag}}_windows_x64.zip
